### ISSUE TITLE
error when running the ingest script

### ISSUE THREAD

**Issue by davidholiday** [tequalsme/accumulo-wikisearch#2]
ahoy hoy

am learning the hadoop/zookeeper/accumulo stuff and was jazzed to come across this repo as it means I can easily ingest a bunch of data into my accumulo instance and work with it. unfortunately, after I followed the README steps and attempted to run the ingest.sh script, I get the following:

tl;dr -- Exception in thread "main" org.apache.accumulo.core.client.AccumuloException: org.apache.thrift.TApplicationException: Internal error processing authenticateUser 

**vagrant@accumulo-dev-box:/vagrant/accumulo-wikisearch/ingester/bin$ ./ingest.sh /wiki_dumps
/vagrant/accumulo-wikisearch/ingester/bin
hadoop jar /vagrant/accumulo-wikisearch/ingester/bin/../lib/wikisearch-ingest-1.4.5-SNAPSHOT.jar org.apache.accumulo.examples.wikisearch.ingest.WikipediaIngester -libjars /vagrant/accumulo-wikisearch/ingester/bin/../lib/accumulo-core-1.4.4.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/cloudtrace-1.4.4.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/commons-codec-1.5.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/commons-lang-2.4.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/guava-14.0.1.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/hadoop-core-0.20.203.0.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/libthrift-0.6.1.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/lucene-analyzers-3.0.2.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/lucene-core-3.0.2.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/lucene-wikipedia-3.0.2.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/protobuf-java-2.3.0.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/wikisearch-ingest-1.4.5-SNAPSHOT.jar,/vagrant/accumulo-wikisearch/ingester/bin/../lib/zookeeper-3.3.1.jar -conf /vagrant/accumulo-wikisearch/ingester/bin/../conf/wikipedia.xml -Dwikipedia.input=/wiki_dumps
15/03/05 00:58:48 INFO security.UserGroupInformation: JAAS Configuration already set up for Hadoop, not re-installing.
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.3.1-942149, built on 05/07/2010 17:14 GMT
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:host.name=accumulo-dev-box
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:java.version=1.7.0_76
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-7-oracle/jre
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/vagrant/hadoop-0.20.2-cdh3u3/conf:/usr/lib/jvm/java-7-oracle//lib/tools.jar:/home/vagrant/hadoop-0.20.2-cdh3u3:/home/vagrant/hadoop-0.20.2-cdh3u3/hadoop-core-0.20.2-cdh3u3.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/ant-contrib-1.0b3.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/aspectjrt-1.6.5.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/aspectjtools-1.6.5.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-cli-1.2.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-codec-1.4.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-collections-3.2.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-configuration-1.10.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-daemon-1.0.1.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-el-1.0.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-httpclient-3.1.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-io-2.4.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-lang-2.4.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-logging-1.0.4.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-logging-api-1.0.4.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/commons-net-1.4.1.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/core-3.1.1.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/guava-r09-jarjar.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/hadoop-fairscheduler-0.20.2-cdh3u3.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/hsqldb-1.8.0.10.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jackson-core-asl-1.5.2.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jackson-mapper-asl-1.5.2.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jasper-compiler-5.5.12.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jasper-runtime-5.5.12.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jets3t-0.6.1.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jetty-6.1.26.cloudera.1.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jetty-servlet-tester-6.1.26.cloudera.1.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jetty-util-6.1.26.cloudera.1.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jsch-0.1.42.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/junit-4.5.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/kfs-0.2.2.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/log4j-1.2.15.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/mockito-all-1.8.2.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/oro-2.0.8.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/servlet-api-2.5-20081211.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/servlet-api-2.5-6.1.14.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/slf4j-api-1.4.3.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/slf4j-log4j12-1.4.3.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/xmlenc-0.52.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jsp-2.1/jsp-2.1.jar:/home/vagrant/hadoop-0.20.2-cdh3u3/lib/jsp-2.1/jsp-api-2.1.jar::/vagrant/accumulo-wikisearch/ingester/bin/../lib/accumulo-core-1.4.4.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/cloudtrace-1.4.4.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/commons-codec-1.5.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/commons-lang-2.4.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/guava-14.0.1.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/hadoop-core-0.20.203.0.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/libthrift-0.6.1.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/lucene-analyzers-3.0.2.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/lucene-core-3.0.2.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/lucene-wikipedia-3.0.2.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/protobuf-java-2.3.0.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/wikisearch-ingest-1.4.5-SNAPSHOT.jar:/vagrant/accumulo-wikisearch/ingester/bin/../lib/zookeeper-3.3.1.jar
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/home/vagrant/hadoop-0.20.2-cdh3u3/lib/native/Linux-amd64-64
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:os.version=3.2.0-23-generic
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:user.name=vagrant
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/vagrant
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Client environment:user.dir=/vagrant/accumulo-wikisearch/ingester/bin
15/03/05 00:58:49 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.accumulo.core.zookeeper.ZooSession$AccumuloWatcher@5c2e86f5
15/03/05 00:58:49 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181
15/03/05 00:58:49 INFO zookeeper.ClientCnxn: Socket connection established to localhost/127.0.0.1:2181, initiating session
15/03/05 00:58:49 INFO zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14be5b10fc70009, negotiated timeout = 30000
Exception in thread "main" org.apache.accumulo.core.client.AccumuloException: org.apache.thrift.TApplicationException: Internal error processing authenticateUser
    at org.apache.accumulo.core.client.impl.ServerClient.execute(ServerClient.java:78)
    at org.apache.accumulo.core.client.impl.ConnectorImpl.<init>(ConnectorImpl.java:75)
    at org.apache.accumulo.core.client.ZooKeeperInstance.getConnector(ZooKeeperInstance.java:218)
    at org.apache.accumulo.examples.wikisearch.ingest.WikipediaConfiguration.getConnector(WikipediaConfiguration.java:115)
    at org.apache.accumulo.examples.wikisearch.ingest.WikipediaIngester.run(WikipediaIngester.java:142)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
    at org.apache.accumulo.examples.wikisearch.ingest.WikipediaIngester.main(WikipediaIngester.java:65)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:197)
Caused by: org.apache.thrift.TApplicationException: Internal error processing authenticateUser
    at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
    at org.apache.accumulo.core.client.impl.thrift.ClientService$Client.recv_authenticateUser(ClientService.java:423)
    at org.apache.accumulo.core.client.impl.thrift.ClientService$Client.authenticateUser(ClientService.java:403)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.accumulo.cloudtrace.instrument.thrift.TraceWrap$2.invoke(TraceWrap.java:84)
    at com.sun.proxy.$Proxy0.authenticateUser(Unknown Source)
    at org.apache.accumulo.core.client.impl.ConnectorImpl$1.execute(ConnectorImpl.java:78)
    at org.apache.accumulo.core.client.impl.ConnectorImpl$1.execute(ConnectorImpl.java:75)
    at org.apache.accumulo.core.client.impl.ServerClient.executeRaw(ServerClient.java:109)
    at org.apache.accumulo.core.client.impl.ServerClient.execute(ServerClient.java:72)
    ... 11 more**

I came across this from another repo: 

https://github.com/joshelser/node-accumulo/issues/1

and thought it might be germane. do you have any thoughts on what the issue might be?

**Comment by davidholiday** [comment]
argg - n/m. turns out there's an open bug stating wikisearch doesn't work with Accumulo 1.5 (or anything later too, I presume) 

https://issues.apache.org/jira/browse/ACCUMULO-2446
